[colors.primary]
background = '#f7f9ff'
foreground = '#181c20'

[colors.selection]
text = '#181c20'
background = '#cfe5ff'

[colors.cursor]
text = '#f7f9ff'
cursor = '#32628d'

[colors.normal]
black   = '#101418'
red     = '#8c0b0d'
green   = '#0c7209'
yellow  = '#7f7211'
blue    = '#52b7ff'
magenta = '#235077'
cyan    = '#32628d'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52022'
green   = '#178c13'
yellow  = '#998b21'
blue    = '#3170a9'
magenta = '#3fc7ff'
cyan    = '#5961ff'
white   = '#1a1a1a'
