alias cnpm="npm --registry=https://registry.npmmirror.com --cache=$HOME/.npm/.cache/cnpm --disturl=https://npmmirror.com/mirrors/node --userconfig=$HOME/.cnpmrc"
alias e="exit"
alias ls="lsd"
alias la="ls -a"
alias ll="ls -llha"
alias gia="git add"
alias gic="git commit"
alias gicfg="git config"
alias man="man -L zh_CN"
alias ip="ip -c"
