# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

# fastfetch -c /usr/share/fastfetch/presets/examples/10.jsonc

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$HOME/.config/zsh/zsh-newuser-install.zsh"

# Plugins
#source "$HOME/.config/zsh/zsh-vi-mode/zsh-vi-mode.zsh"
source "$HOME/.config/zsh/plugins/zsh-you-should-use/zsh-you-should-use.plugin.zsh"
source "$HOME/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOME/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOME/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "$HOME/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme"

# Other Settings
source "$HOME/.config/zsh/alias.zsh"

# Environment
source "$HOME/.config/zsh/env.zsh"

# conda
source "$HOME/.config/zsh/conda.zsh"

# Yazi
source "$HOME/.config/zsh/yazi.zsh"

# Keymaps
source "$HOME/.config/zsh/keymap.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

